/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE / hand-added for GCC newlib build
 * @brief     最小化的 newlib 系统调用桩。提供这些实现是为了顶替
 *            -specs=nosys.specs 里会在链接期发出
 *            "X is not implemented and will always fail" 警告的同名弱桩。
 *            裸机固件不需要真正的 POSIX 系统调用，这里返回失败/空操作即可。
 *
 *            注意：GCC/newlib 下标准 printf 走 _write（不是 Keil 的 fputc）。
 *            本工程实际打印用 USART1 的 printf_use_dma()，故 _write 留作可选
 *            重定向点：默认空实现，返回写入长度以避免上层报错。
 ******************************************************************************
 */

#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <unistd.h>

/* errno 由 newlib 提供 */
#ifndef errno
extern int errno;
#endif

/* __libc_init_array 等会引用到的环境变量 */
char *__env[1] = { 0 };
char **environ = __env;

void initialise_monitor_handles(void)
{
}

int _getpid(void)
{
    return 1;
}

int _kill(int pid, int sig)
{
    (void)pid;
    (void)sig;
    errno = EINVAL;
    return -1;
}

void _exit(int status)
{
    _kill(status, -1);
    while (1) {
    }   /* 裸机不应返回 */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
    (void)file;
    (void)ptr;
    (void)len;
    return 0;
}

/* 标准 printf 的输出落点。默认丢弃但报告成功，避免上层缓冲逻辑出错。
 * 若想让普通 printf 也走 USART1，可在此调用 HAL_UART_Transmit。 */
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
    (void)file;
    (void)ptr;
    return len;
}

int _close(int file)
{
    (void)file;
    return -1;
}

int _fstat(int file, struct stat *st)
{
    (void)file;
    st->st_mode = S_IFCHR;
    return 0;
}

int _isatty(int file)
{
    (void)file;
    return 1;
}

int _lseek(int file, int ptr, int dir)
{
    (void)file;
    (void)ptr;
    (void)dir;
    return 0;
}
